version: '3'
services:
  web:
    environment:
      - CHOKIDAR_USEPOLLING=true npm start
    
    tests: 
      build: 
        context: .
        dockerfile : Dockerfile.dev
      volumes:
        - /app/node_modules
        - .:/app 
      command : ["npm" ,"run" , "test"]
    